import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import Footer from "@/compound/footer";
import Navbar from "@/compound/nav";
import Offer from "@/compound/offer";

const geistSans = GeistSans;

const geistMono = GeistMono;

export const metadata = {
  title: "Ghar Basai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
      <Offer />
      <Navbar />
      {children}
      <Footer />
    </body>
    </html >
  );
}