export const tourData = [
	{
		id: "tour-1",
		title: "Himalayan Trekking Expedition",
		location: "Nepal",
		price: "5,000",
		reviews: "980 reviews",
		rating: 4.8,
		image: "/image/himalayan-trek.jpg",
		description: "An unforgettable 14-day trekking adventure through the stunning Himalayan range, perfect for experienced hikers.",
		activities: ["Trekking", "Camping", "Mountain Climbing", "Stargazing"],
	},
	{
		id: "tour-2",
		title: "Golden Triangle Tour",
		location: "India",
		price: "1,500",
		reviews: "2,500 reviews",
		rating: 4.9,
		image: "/image/golden-triangle.jpg",
		description: "A classic 7-day tour covering the historical wonders of Delhi, Agra, and Jaipur.",
		activities: ["Sightseeing", "Historical Tours", "Shopping", "Food Tasting"],
	},
	{
		id: "tour-3",
		title: "Kerala Backwaters Cruise",
		location: "Kerala, India",
		price: "2,200",
		reviews: "1,800 reviews",
		rating: 4.7,
		image: "/image/backwaters.jpg",
		description: "Relax on a houseboat as you glide through the serene backwaters of Kerala, a true escape from the city.",
		activities: ["Houseboat Cruise", "Village Tours", "Bird Watching", "Ayurvedic Spa"],
	},
	{
		id: "tour-4",
		title: "Safari in Masai Mara",
		location: "Kenya",
		price: "8,000",
		reviews: "1,100 reviews",
		rating: 4.9,
		image: "/image/safari.jpg",
		description: "A wildlife photographer's dream, this safari tour offers a chance to see the 'Big Five' in their natural habitat.",
		activities: ["Game Drives", "Hot Air Balloon Safari", "Cultural Visits"],
	},
	{
		id: "tour-5",
		title: "Cherry Blossom Festival Tour",
		location: "Tokyo, Japan",
		price: "3,500",
		reviews: "3,200 reviews",
		rating: 5.0,
		image: "/image/cherry-blossom.jpg",
		description: "Witness the stunning beauty of Japan during the cherry blossom season with this guided cultural tour.",
		activities: ["Temple Visits", "Tea Ceremony", "Festival Viewing", "Local Market Exploration"],
	},
];